# Site settings
<<<<<<< HEAD
title:          코딩 기록
description:    "코딩 기록용 블로그"
baseurl:        ""
url:            "https://adc0612.github.io"
=======
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chesterhow.github.io"
>>>>>>> e10ff8e7c3ba83985303a500099ec06c021b190f

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Dohu Jeon
  url:          https://adc0612.github.io
  email:        adc0612@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
