# Site settings
title:          coroc
description:    "코딩 기록 블로그"
baseurl:        ""
url:            "https://adc0612.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Dohu Jeon
  url:          https://adc0612.github.io
  email:        adc0612@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
img_url: /assets/img
category_list: [ algorithm, git, react, vue, typescript]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

